language: common-lisp
sudo: required
os:
  - linux
  - osx

env:
  - LISP=sbcl-bin
  - LISP=ccl-bin

matrix:
  include:
    - env: LISP=sbcl/1.4.15
      os: linux
    - env: LISP=sbcl/1.5.2
      os: osx
    - language: nix
      os: linux
      env:
      script: nix-build default.nix && echo -shcl-run-tests | ./result/bin/shcl
      install: true
  allow_failures:
    - env: LISP=sbcl-bin
      os: linux
    - env: LISP=sbcl-bin
      os: osx

install:
  - ./ci/install

script:
  - make LISP='ros -s cffi-grovel run --'
  - echo -shcl-run-tests | ./run-shcl
