#!/bin/sh

set -e

if [ "${TRAVIS_OS_NAME}" = linux ]; then
    sudo apt-get update
    sudo apt-get install clang
    sudo apt-get install libedit-dev
elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew install libedit
fi

curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
